package com.akif.enums;

public enum EmailType {

    RENTAL_CONFIRMATION,
    PAYMENT_RECEIPT,
    PICKUP_REMINDER,
    RETURN_REMINDER,
    CANCELLATION_CONFIRMATION,

    DAMAGE_REPORTED,
    DAMAGE_ASSESSED,
    DAMAGE_CHARGED,
    DAMAGE_CHARGE_FAILED,
    DAMAGE_DISPUTED,
    DAMAGE_RESOLVED
}

